config/routes.rb
Rails.application.routes.draw do

  resources :labels, only: [:show]

  resources :topics do
    resources :posts, except: [:index]    
  end
  
  resources :posts, only: [] do
     resources :comments, only: [:create, :destroy]
     resources :favorites, only: [:create, :destroy]
     
     post '/up-vote' => 'votes#up_vote', as: :up_vote
     post '/down-vote' => 'votes#down_vote', as: :down_vote
   end
  
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

  get 'about' => 'welcome#about'
  
  root 'welcome#index'
  
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :update]
      resources :topics, except: [:edit, :new] do
        resources :posts, only: [:create, :update, :destroy, :index]
      end
    end
  end
end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  
  validates :body, length: {minimum: 5}, presence: true
  validates :user, presence: true
  
  default_scope { order('updated_at ASC') }
  
  after_create :send_favorite_emails
 
   private
 
   def send_favorite_emails
     post.favorites.each do |favorite|
       FavoriteMailer.new_comment(favorite.user, post, self).deliver_now
     end
   end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  
  def display_favorites
    
    
  end
end

app/models/label.rb
class Label < ActiveRecord::Base
    has_many :labelings

    has_many :topics, through: :labelings, source: :labelable, source_type: :Topic
    has_many :posts, through: :labelings, source: :labelable, source_type: :Post
    
    def self.update_labels(label_string)
        return Label.none if label_string.blank?
        
        label_string.split(",").map do |label|
        Label.find_or_create_by(name: label.strip)
     end
    end
end

app/models/labeling.rb
class Labeling < ActiveRecord::Base
 
    belongs_to :labelable, polymorphic: true
    belongs_to :label
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings
  has_many :favorites, dependent: :destroy
  
  default_scope { order('rank DESC') }
  scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }
  
  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true
  
   def up_votes
     votes.where(value: 1).count
   end
 
   def down_votes
     votes.where(value: -1).count
   end
 
   def points
     votes.sum(:value)
   end
   
   def update_rank
     age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
     new_rank = points + age_in_days
     update_attribute(:rank, new_rank)
   end
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/sponsored_post.rb
class SponsoredPost < ActiveRecord::Base
    belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
    has_many :posts, dependent: :destroy
    has_many :labelings, as: :labelable
    has_many :labels, through: :labelings
    
    scope :publicly_viewable, -> { where(public: true) }
    scope :privately_viewable, -> { where(public: false) }
    scope :visible_to, -> (user) { user ? all : publicly_viewable }
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :votes, dependent: :destroy
    has_many :favorites, dependent: :destroy
    before_save { self.email = email.downcase }
    before_save { self.role ||= :member }
    before_create :generate_auth_token

    validates :name, length: { minimum: 1, maximum: 100 }, presence: true
    validates :password, presence: true, length: { minimum: 6 }, if: "password_digest.nil?"
    validates :password, length: { minimum: 6 }, allow_blank: true
    validates :email,
             presence: true,
             uniqueness: { case_sensitive: false },
             length: { minimum: 3, maximum: 254 }

   has_secure_password
   
   enum role: [:member, :admin]
   
   def favorite_for(post)
     favorites.where(post_id: post.id).first
   end
   
   def avatar_url(size)
     gravatar_id = Digest::MD5::hexdigest(self.email).downcase
     "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
   end
   
   def generate_auth_token
     loop do
         self.auth_token = SecureRandom.base64(64)
         break unless User.find_by(auth_token: auth_token)
     end
   end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  after_save :update_post
  
  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }, presence: true
  
  private
  def update_post
     post.update_rank
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def faq
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
    def user_is_authorized_for_comment?(comment)
      current_user && (current_user == comment.user || current_user.admin?)
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
    def labels_to_buttons(labels)
      raw labels.map { |l| link_to l.name, label_path(id: l.id), class: 'btn-xs btn-primary' }.join(' ')
    end
end

app/helpers/posts_helper.rb
module PostsHelper
    def user_is_authorized_for_post?(post)
        current_user && (current_user == post.user || current_user.admin? || current_user.moderator?)
   end
end

app/helpers/sessions_helper.rb
module SessionsHelper
   
   def create_session(user)
     session[:user_id] = user.id
   end
 
   def destroy_session(user)
     session[:user_id] = nil
   end
 
   def current_user
     User.find_by(id: session[:user_id])
   end
    
end

app/helpers/topics_helper.rb
module TopicsHelper
    def user_is_authorized_for_topics?
        current_user && (current_user.admin? || current_user.moderator?)
   end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>About Bloccit</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-10">
    <p class="lead">Just like Reddit, Bloccit is an app where you can discuss topics.</p>
    <h3>Where you can:</h3><ul>
      <li><h5>Securely sign up for an account</h5></li>
      <li><h5>Create a new post within any of the topics</h5></li>
      <li><h5>Comment on existing posts</h5></li>
      <li><h5>Favorite posts you enjoy to revisit later</h5></li>
      <li><h5>Vote posts up or down to provide feedback</h5></li>
    </ul>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <hr>
    <blockquote>
      <p><small>Bloccit is a project hand-crafted by <a href="http://drianhillman.me" target="_blank">Drian Hillman</a> during the Software Engineering Track at <a href="https://www.bloc.io" target="_blank">BLOC</a>.</small></p>
    </blockquote>
  </div>
</div>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1>Bloccit</h1>
  <p>Bloccit is a resource for sharing links with your friends!</p>
  <p>
    <%= link_to "Sign In", new_session_path %> or
    <%= link_to "Sign Up", new_user_path, class: 'btn btn-primary' %> today!
  </p>
</div>

<div class="row">
  <div class="col-md-4">
    <h2>Solves world hunger</h2>
    <p>Bloccit will deliver food and water to those in need, all over the world.</p>
  </div>
  <div class="col-md-4">
    <h2>Eliminates poverty</h2>
    <p>Bloccit will deliver money and education to those in need, all over the world.</p>
  </div>
  <div class="col-md-4">
    <h2>Makes you better looking</h2>
    <p>Bloccit will make you better looking: it's scientifically proven to make men & women look like their best selves.</p>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <blockquote style="margin-top: 48px;">
      <p class="lead">Bloccit is a fully functional prototype but contains placeholder content.</p>
    </blockquote>
  </div>
</div>